/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Material Design 3 Color Palette
        'primary': '#000d22',
        'on-primary': '#ffffff',
        'primary-container': '#002349',
        'on-primary-container': '#718bb7',
        'primary-fixed': '#d5e3ff',
        'primary-fixed-dim': '#adc8f6',
        'on-primary-fixed': '#001b3c',
        'on-primary-fixed-variant': '#2c476f',

        'secondary': '#775a19',
        'on-secondary': '#ffffff',
        'secondary-container': '#fed488',
        'on-secondary-container': '#785a1a',
        'secondary-fixed': '#ffdea5',
        'secondary-fixed-dim': '#e9c176',
        'on-secondary-fixed': '#261900',
        'on-secondary-fixed-variant': '#5d4201',

        'tertiary': '#220400',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#471000',
        'on-tertiary-container': '#d07051',
        'tertiary-fixed': '#ffdbd0',
        'tertiary-fixed-dim': '#ffb59e',
        'on-tertiary-fixed': '#390b00',
        'on-tertiary-fixed-variant': '#7a2f15',

        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',

        'background': '#f8f9fa',
        'on-background': '#191c1d',
        'surface': '#f8f9fa',
        'on-surface': '#191c1d',
        'surface-variant': '#e1e3e4',
        'on-surface-variant': '#43474e',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'surface-tint': '#455f88',

        'outline': '#74777f',
        'outline-variant': '#c4c6cf',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        'inverse-primary': '#adc8f6',
      },
      fontFamily: {
        'display-lg': ['Playfair Display', 'serif'],
        'headline-md': ['Playfair Display', 'serif'],
        'title-sm': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'body-md': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'label-caps': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        display: ['Playfair Display', 'serif'],
        body: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'title-sm': ['18px', { lineHeight: '24px', letterSpacing: '0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '700' }],
      },
      spacing: {
        'unit': '4px',
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '40px',
        'gutter': '16px',
        'margin-mobile': '20px',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      boxShadow: {
        'soft': '0px 4px_20px rgba(0,13,34,0.04)',
        'elegant': '0px 20px 40px rgba(0, 0, 0, 0.3)',
      },
      backdropBlur: {
        'sm': '4px',
      },
      letterSpacing: {
        'wider': '0.15em',
        'widest': '0.2em',
      }
    },
  },
  plugins: [],
}
